AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bookwalker-booklist

Parameters:
  Name:
    Type: String
    Description: Your name
  BookwalkerSecretArn:
    Type: String
    Description: ARN of the secrets for the login credentials in Secrets Manager
  OutputS3Bucket:
    Type: String
    Description: Output S3 bucket name
  OutputS3Prefix:
    Type: String
    Description: Output S3 object prefix

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: bookwalker.main
      Runtime: ruby2.7
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          NAME: !Ref Name
          BOOKWALKER_SECRET_ARN: !Ref BookwalkerSecretArn
          BOOKWALKER_S3_BUCKET: !Ref OutputS3Bucket
          BOOKWALKER_S3_PREFIX: !Ref OutputS3Prefix
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
      Policies:
        - S3WritePolicy:
            BucketName: !Ref OutputS3Bucket
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref BookwalkerSecretArn
